/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiredtiger_db_Session */

#ifndef _Included_com_wiredtiger_db_Session
#define _Included_com_wiredtiger_db_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiredtiger_db_Session
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiredtiger_db_Session_create
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_wiredtiger_db_Session
 * Method:    open_cursor
 * Signature: (Ljava/lang/String;Lcom/wiredtiger/db/Cursor;Ljava/lang/String;)Lcom/wiredtiger/db/Cursor;
 */
JNIEXPORT jobject JNICALL Java_com_wiredtiger_db_Session_open_1cursor
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     com_wiredtiger_db_Session
 * Method:    close
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiredtiger_db_Session_close
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
