/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiredtiger_db_Connection */

#ifndef _Included_com_wiredtiger_db_Connection
#define _Included_com_wiredtiger_db_Connection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiredtiger_db_Connection
 * Method:    open_session
 * Signature: (Ljava/lang/String;)Lcom/wiredtiger/db/Session;
 */
JNIEXPORT jobject JNICALL Java_com_wiredtiger_db_Connection_open_1session
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiredtiger_db_Connection
 * Method:    close
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiredtiger_db_Connection_close
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
