/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiredtiger_db_WiredTiger */

#ifndef _Included_com_wiredtiger_db_WiredTiger
#define _Included_com_wiredtiger_db_WiredTiger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiredtiger_db_WiredTiger
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/wiredtiger/db/Connection;
 */
JNIEXPORT jobject JNICALL Java_com_wiredtiger_db_WiredTiger_open
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
