/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiredtiger_db_Cursor */

#ifndef _Included_com_wiredtiger_db_Cursor
#define _Included_com_wiredtiger_db_Cursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiredtiger_db_Cursor
 * Method:    putKeyString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiredtiger_db_Cursor_putKeyString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiredtiger_db_Cursor
 * Method:    putValueString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiredtiger_db_Cursor_putValueString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiredtiger_db_Cursor
 * Method:    insert
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiredtiger_db_Cursor_insert
  (JNIEnv *, jobject);

/*
 * Class:     com_wiredtiger_db_Cursor
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiredtiger_db_Cursor_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_wiredtiger_db_Cursor
 * Method:    search
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiredtiger_db_Cursor_search
  (JNIEnv *, jobject);

/*
 * Class:     com_wiredtiger_db_Cursor
 * Method:    getValueString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiredtiger_db_Cursor_getValueString
  (JNIEnv *, jobject);

/*
 * Class:     com_wiredtiger_db_Cursor
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiredtiger_db_Cursor_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
